"""Locked English (IN) bench: 6 TTS models × 11 voices = 550 clips."""

from __future__ import annotations

from typing import Any

LOCALE = "en-IN"
RUN_SLUG = "en-in-11-2026"

# One row per provider/model in `models` table (leaderboard entity).
MODEL_GROUPS: list[dict[str, Any]] = [
    {
        "slug": "google-gemini-en-in",
        "name": "Gemini 3.1 Flash TTS",
        "provider": "Google",
        "api_slug": "google/gemini-3.1-flash-tts-preview",
        "color": "#4285f4",
        "sort_order": 1,
    },
    {
        "slug": "sarvam-bulbul-en-in",
        "name": "Sarvam Bulbul v3",
        "provider": "Sarvam",
        "api_slug": "bulbul:v3",
        "color": "#f97316",
        "sort_order": 2,
    },
    {
        "slug": "microsoft-mai-en-in",
        "name": "MAI-Voice-2",
        "provider": "Microsoft",
        "api_slug": "microsoft/mai-voice-2",
        "color": "#0078d4",
        "sort_order": 3,
    },
    {
        "slug": "fish-s21-en-in",
        "name": "Fish S2.1 Pro Free",
        "provider": "Fish Audio",
        "api_slug": "fish-audio/s2.1-pro-free:free",
        "color": "#22c55e",
        "sort_order": 4,
    },
    {
        "slug": "elevenlabs-en-in",
        "name": "ElevenLabs v3",
        "provider": "ElevenLabs",
        "api_slug": "eleven_v3",
        "color": "#111827",
        "sort_order": 5,
    },
    {
        "slug": "cartesia-sonic-en-in",
        "name": "Cartesia Sonic 3.5",
        "provider": "Cartesia",
        "api_slug": "sonic-3.5",
        "color": "#6366f1",
        "sort_order": 6,
    },
]

# Synthesis + `model_voices` rows (multiple per model group).
VOICE_CONFIGS: list[dict[str, Any]] = [
    {
        "rank_slug": "01_google_gemini_kore",
        "model_slug": "google-gemini-en-in",
        "voice_key": "Kore",
        "voice_label": "Kore — firm (en-IN)",
        "is_default": True,
        "backend": "openrouter",
        "model": "google/gemini-3.1-flash-tts-preview",
        "voice": "Kore",
        "response_format": "pcm",
        "ext": "wav",
        "provider_options": {"google": {"language_code": "en-IN"}},
    },
    {
        "rank_slug": "02_google_gemini_charon",
        "model_slug": "google-gemini-en-in",
        "voice_key": "Charon",
        "voice_label": "Charon — informative (en-IN)",
        "is_default": False,
        "backend": "openrouter",
        "model": "google/gemini-3.1-flash-tts-preview",
        "voice": "Charon",
        "response_format": "pcm",
        "ext": "wav",
        "provider_options": {"google": {"language_code": "en-IN"}},
    },
    {
        "rank_slug": "03_sarvam_ishita",
        "model_slug": "sarvam-bulbul-en-in",
        "voice_key": "ishita",
        "voice_label": "Ishita — en-IN female",
        "is_default": True,
        "backend": "sarvam",
        "model": "bulbul:v3",
        "voice": "ishita",
        "target_language_code": "en-IN",
        "ext": "mp3",
    },
    {
        "rank_slug": "04_sarvam_ratan",
        "model_slug": "sarvam-bulbul-en-in",
        "voice_key": "ratan",
        "voice_label": "Ratan — en-IN male",
        "is_default": False,
        "backend": "sarvam",
        "model": "bulbul:v3",
        "voice": "ratan",
        "target_language_code": "en-IN",
        "ext": "mp3",
    },
    {
        "rank_slug": "05_mai_swara",
        "model_slug": "microsoft-mai-en-in",
        "voice_key": "hi-IN-SwaraNeural",
        "voice_label": "Swara — Hinglish female",
        "is_default": True,
        "backend": "openrouter",
        "model": "microsoft/mai-voice-2",
        "voice": "hi-IN-SwaraNeural",
        "response_format": "mp3",
        "ext": "mp3",
    },
    {
        "rank_slug": "06_mai_aarav",
        "model_slug": "microsoft-mai-en-in",
        "voice_key": "hi-IN-AaravNeural",
        "voice_label": "Aarav — Hinglish male",
        "is_default": False,
        "backend": "openrouter",
        "model": "microsoft/mai-voice-2",
        "voice": "hi-IN-AaravNeural",
        "response_format": "mp3",
        "ext": "mp3",
    },
    {
        "rank_slug": "07_fish_indian_lady",
        "model_slug": "fish-s21-en-in",
        "voice_key": "b1a1d760d9604bdb957a56eec3460f1b",
        "voice_label": "Indian Lady — female",
        "is_default": True,
        "backend": "openrouter",
        "model": "fish-audio/s2.1-pro-free:free",
        "voice": "b1a1d760d9604bdb957a56eec3460f1b",
        "response_format": "mp3",
        "ext": "mp3",
    },
    {
        "rank_slug": "08_fish_anurag",
        "model_slug": "fish-s21-en-in",
        "voice_key": "5b7d0c126b37409197f570a61a18b927",
        "voice_label": "Anurag — male",
        "is_default": False,
        "backend": "openrouter",
        "model": "fish-audio/s2.1-pro-free:free",
        "voice": "5b7d0c126b37409197f570a61a18b927",
        "response_format": "mp3",
        "ext": "mp3",
    },
    {
        "rank_slug": "09_elevenlabs_raju",
        "model_slug": "elevenlabs-en-in",
        "voice_key": "pzxut4zZz4GImZNlqQ3H",
        "voice_label": "Raju — Natural Conversationalist",
        "is_default": True,
        "backend": "elevenlabs",
        "model": "eleven_v3",
        "voice": "pzxut4zZz4GImZNlqQ3H",
        "ext": "mp3",
    },
    {
        "rank_slug": "10_cartesia_arushi",
        "model_slug": "cartesia-sonic-en-in",
        "voice_key": "95d51f79-c397-46f9-b49a-23763d3eaa2d",
        "voice_label": "Arushi — Hinglish female",
        "is_default": True,
        "backend": "cartesia",
        "model": "sonic-3.5",
        "voice": "95d51f79-c397-46f9-b49a-23763d3eaa2d",
        "language": "hi",
        "ext": "mp3",
    },
    {
        "rank_slug": "11_cartesia_rohan",
        "model_slug": "cartesia-sonic-en-in",
        "voice_key": "4877b818-c7fe-4c89-b1cf-eadf8e23da72",
        "voice_label": "Rohan — hi-IN male",
        "is_default": False,
        "backend": "cartesia",
        "model": "sonic-3.5",
        "voice": "4877b818-c7fe-4c89-b1cf-eadf8e23da72",
        "language": "hi",
        "ext": "mp3",
    },
]

MODEL_BY_SLUG = {m["slug"]: m for m in MODEL_GROUPS}
